image: archlinux
packages:
    - hugo
sources:
    - https://git.sr.ht/~shreyasminocha/shreyasminocha.me
oauth: pages.sr.ht/PAGES:RW
environment:
    site: shreyasminocha.me
tasks:
    - package: |
          cd shreyasminocha.me
          hugo
          tar -C public -cvz . > ../site.tar.gz
    - deploy: |
          acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
