line-length: false

list-marker-space:
    ul_multi: 3
    ul_single: 3

ul-indent:
    indent: 4

# for mdx, which technically isn't even supported by markdownlint
no-inline-html: false

# causes false positives with mdx comments
no-space-in-emphasis: false
