---
extends: stylelint-config-standard

rules:
    indentation: 4
    selector-attribute-operator-space-after: 'always'
    selector-attribute-operator-space-before: 'always'

    # Re-enable some time
    no-descending-specificity: null
