title: Shreyas Minocha | Node.js+
baseUrl: https://shreyasminocha.me
googleAnalytics: UA-90885717-1
paginate: 5
disqusShortname: shreyasminocha

params:
    title: Shreyas Minocha
    description: An Indian male who loves all things tech
    name: Shreyas Minocha
    bio: Computer fanatic
    languageCode: en-uk
    github: shreyasminocha
    stackoverflow: 3363528/shreyasminocha
    email: shreyas@shreyasminocha.me
    devto: shreyasminocha
    codepen: shreyasminocha

useSummaryIfNoDescription: false
assetDir: static
publishDir: rendered

blackfriday:
    noreferrerLinks: true
    nofollowLinks: true

pygmentsCodeFences: true
pygmentsUseClasses: true
