languageCode = "en-us"
title = "Shreyas Minocha | A young computer enthusiast"
theme = "hugo-steam-theme"
disqusShortname = "shreyasminocha"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-90885717-1', 'auto');ga('send', 'pageview');</script>"
# Number of posts per page
paginate = 5

[params]
	title = "Shreyas Minocha"
	subtitle = "Just a kid who loves tech and math"
	copyright = "All rights reserved."

	# You can choose between green, orange, red and blue.
	themecolor = "red"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Shreyas Minocha"
	bio = "A young developer and math lover"
	description = "An Indian kid who loves all things tech"

	# Link your social networks (optional)
	location = "Hyderabad, India"
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "shreyasminocha"
	gitlab = ""
	bitbucket = ""
	stackoverflow = "3363528/shreyasminocha"
	email = "shreyas@shreyasminocha.me"

	# Customize or translate the strings
	keepReadingStr = "Continue reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
