---
baseUrl: https://shreyasminocha.me
disqusShortname: shreyasminocha
googleAnalytics: UA-90885717-1
languageCode: en-uk
paginate: 5
params:
  backtotopStr: Back to top
  bio: A young developer
  copyright: All rights reserved.
  description: An Indian kid who loves all things tech
  email: shreyas@shreyasminocha.me
  favicon: img/favicon.ico
  github: shreyasminocha
  keepReadingStr: Continue reading
  location: Hyderabad, India
  name: Shreyas Minocha
  pageNotFoundTitle: 404 - Page not found
  shareStr: Share
  stackoverflow: 3363528/shreyasminocha
  subtitle: Just a kid who loves tech
  themecolor: red
  title: Shreyas Minocha
useSummaryIfNoDescription: false
assetDir: static
theme: hugo-steam-theme
title: Shreyas Minocha | A young computer enthusiast
