title: Shreyas Minocha
baseUrl: https://shreyasminocha.me
paginate: 7

params:
    title: Shreyas Minocha
    description: "Shreyas Minocha's little website."
    name: Shreyas Minocha
    languageCode: en-uk

useSummaryIfNoDescription: false
assetDir: static
publishDir: public

blackfriday:
    noreferrerLinks: true
    nofollowLinks: true

pygmentsCodeFences: true
pygmentsUseClasses: true

ignoreFiles:
    - content/license.md
    - content/blog/dropped
