title: Shreyas Minocha
baseUrl: https://shreyasminocha.me
paginate: 7

params:
    title: Shreyas Minocha
    description: "Shreyas Minocha's personal website."
    name: Shreyas Minocha
    languageCode: en-in

useSummaryIfNoDescription: false
assetDir: static
publishDir: public

blackfriday:
    noreferrerLinks: true
    nofollowLinks: true

pygmentsCodeFences: true
pygmentsUseClasses: true

ignoreFiles:
    - content/index.md # transcluded by layouts/index.html
    - content/license.md
    - content/blog/dropped
