title: Shreyas Minocha | A young computer enthusiast
baseUrl: https://shreyasminocha.me
googleAnalytics: UA-90885717-1
paginate: 5
disqusShortname: shreyasminocha

params:
    title: Shreyas Minocha
    description: An Indian kid who loves all things tech
    name: Shreyas Minocha
    bio: A young developer
    email: shreyas@shreyasminocha.me
    github: shreyasminocha
    stackoverflow: 3363528/shreyasminocha
    languageCode: en-uk

useSummaryIfNoDescription: false
assetDir: static
publishDir: rendered
