title: Shreyas Minocha's slice of the interweb
baseUrl: https://shreyasminocha.me
paginate: 5

params:
    title: Shreyas Minocha
    description: "Shreyas Minocha is: an open source lover, an online privacy advocate, a developer, and a student. This is his little website."
    name: Shreyas Minocha
    languageCode: en-uk
    github: shreyasminocha
    stackoverflow: 3363528/shreyasminocha
    email: shreyas@shreyasminocha.me
    devto: shreyasminocha
    codepen: shreyasminocha

disqusShortname: shreyasminocha

useSummaryIfNoDescription: false
assetDir: static
publishDir: rendered

blackfriday:
    noreferrerLinks: true
    nofollowLinks: true

pygmentsCodeFences: true
pygmentsUseClasses: true

ignoreFiles:
    - content/license.md
    - content/blog/dropped
